In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding


In [2]:
reviews = ['nice food',
           'amazing restaurant',
           'too good',
           'just loved it!',
           'will go again',
           'horrible food',
           'never go there',
           'poor service',
           'poor quality',
           'needs improvement']

sentiment = np.array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0])


In [4]:
one_hot("amazing restaurant", 30)


[19, 17]

In [5]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)

[[6, 3], [19, 17], [11, 14], [23, 22, 23], [3, 2, 3], [27, 3], [24, 2, 29], [29, 20], [29, 18], [5, 24]]


In [6]:
max_length = 4
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)

[[ 6  3  0  0]
 [19 17  0  0]
 [11 14  0  0]
 [23 22 23  0]
 [ 3  2  3  0]
 [27  3  0  0]
 [24  2 29  0]
 [29 20  0  0]
 [29 18  0  0]
 [ 5 24  0  0]]


In [7]:
embeded_vector_size = 5

model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length,name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [8]:
X = padded_reviews
y = sentiment


In [9]:
model.compile(optimizer='adam', loss='binary_crossentropy',
              metrics=['accuracy'])
print(model.summary())


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 4, 5)              150       
                                                                 
 flatten (Flatten)           (None, 20)                0         
                                                                 
 dense (Dense)               (None, 1)                 21        
                                                                 
Total params: 171
Trainable params: 171
Non-trainable params: 0
_________________________________________________________________
None


In [10]:
model.fit(X, y, epochs=50, verbose=0)


In [11]:
# evaluate the model
loss, accuracy = model.evaluate(X, y)
accuracy


1/1 [==============================] - 0s 259ms/step - loss: 0.6330 - accuracy: 1.0000


1.0

In [12]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)


30

In [13]:
weights[13]


array([ 0.04060091, -0.04407729,  0.04121878,  0.01274506, -0.02712807],
      dtype=float32)

In [14]:
weights[4]


array([-0.04643166,  0.03625249, -0.02279907,  0.00930836,  0.0009882 ],
      dtype=float32)

In [15]:
weights[16]


array([ 0.03167155, -0.01691829, -0.02361698, -0.00102652,  0.03584741],
      dtype=float32)